NAME = push_swap

SRC =	*.c

LIB = push_swap.h

FLAGS = -Wall -Wextra -Werror

CC = gcc

all: $(NAME)

$(NAME):
	$(CC) $(SRC) -o $(NAME)

clean:
	rm -f $(NAME)

fclean: clean

re: clean all